### ISSUE TITLE
Doesn't compile with 4.07

### ISSUE THREAD

**Issue by Kakadu** [ocaml/ocaml-lsp#103]
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocaml-lsp-server failed at "/home/kakadu/.opam/4.07.1+fp+flambda/bin/dune build -j 7 --root . --ignore-promoted-rules --no-config
        --profile release ocaml-lsp-server.install".

#=== ERROR while compiling ocaml-lsp-server.~dev ==============================#
# context     2.0.5 | linux/x86_64 | ocaml-variants.4.07.1+fp+flambda | pinned(git+file:///home/kakadu/asp/ocaml-lsp#master#b1168b8d)
# path        ~/.opam/4.07.1+fp+flambda/.opam-switch/build/ocaml-lsp-server.~dev
# command     ~/.opam/4.07.1+fp+flambda/bin/dune build -j 7 --root . --ignore-promoted-rules --no-config --profile release ocaml-lsp-server.install
# exit-code   1
# env-file    ~/.opam/log/ocaml-lsp-server-19335-ebe0e0.env
# output-file ~/.opam/log/ocaml-lsp-server-19335-ebe0e0.out
### output ###
# File "vendor/merlin/src/ocaml/preprocess/parser_raw.ml", line 5, characters 2-42:
# Error: Unbound value MenhirLib.StaticVersion.require_20190924
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Easy_format, and its interface was not compiled with -opaque
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Bi_outbuf, and its interface was not compiled with -opaque
# File "_none_", line 1:
# Warning 58: no cmx file was found in path for module Bi_share, and its interface was not compiled with -opaque



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-lsp-server ~dev
+- 
- No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.

➜  ocaml-lsp git:(master) ✗ opam list|grep menhir                                                                                           4.07.1+fp+flambda
55:menhir                  20190924          An LR(1) parser generator
```

**Comment by rgrinberg** [comment]
Is this caused by #98 @rusty-key ?

**Comment by Kakadu** [comment]
It is better now. Maybe some kind of local misunderstanding...

Any chance that you can add CI icon to make users sure that problem is not in the source?

**Comment by rgrinberg** [comment]
Someone else will have to do it and maintain the compat on 4.07. If you have time to do so, your help would be appreciated.

The time I can afford to spend on supporting older versions of OCaml is quite limited. I would much rather work on making 4.10 work.

**Comment by Kakadu** [comment]
@rgrinberg I totally agree with your intuition but adding CI build for 4.07 (without actually supporting 4.07) should be a one time task. It seems it can't be done by third-party random people because it require knowing where you do actually do CI builds...

**Comment by rusty-key** [comment]
Hm, I had this problem before the mentioned PR was merged https://github.com/ocaml/ocaml-lsp/pull/98. After that, `ocaml-lsp` compiles without problem.

If you look at the actual change, the error doesn't make sense:
https://github.com/rgrinberg/merlin/compare/fb90bf00d3c6b444efc1f38f4c8ca282e8d52a8e...7d8f5cfa5dbc9d676f88cc4697784c1a15432c46#diff-2ec597c3c8fbe5934b4076a1b3de5669
Why would compiler complain about `menhir.20190924` if the only mention of it was removed?

**Comment by giltho** [comment]
Missclick
We can easily add the 4.07 pipeline and we'd get a badge for free.
However, I'd prefer if the readme could display a different badge for every version of OCaml in an array at the beginning of the README file. In particular, that would reduce the amount of issues that are being created regarding OCaml 4.10.
I haven't yet had the time to understand what's the best way of generating dynamically several different badges using github action...

**Comment by imbsky** [comment]
I think it's possible to show the build status of each workflow by using [shields.io](https://shields.io), but I don't think that is necessary.

**Comment by giltho** [comment]
Ok I misunderstood I thought this wasn't fixed but actually it is
A build shield has been added in #179 although there's is only one global, not one per version, but it's ok
