### ISSUE TITLE
Compilation failure on FreeBSD 13,2

### ISSUE THREAD

**Issue by avysk** [ocaml/ocaml-lsp#1069]
```
opam install ocaml-lsp-server
[blah]
┌─ The following actions failed
│ λ build ocaml-lsp-server 1.15.1-5.0
└─
```
I believe the relevant error is ` submodules/lev/lev/vendor/ev.c:510:11: fatal error: sys/statfs.h: No such file or directory`. Indeed, there is no `sys/statfs.h` on FreeBSD; I think it is specific for GNU C library.

```
🌐 eldanna in ~
❯ uname -srm
FreeBSD 13.2-RELEASE amd64
🌐 eldanna in ~
❯ ocamlc --version
5.0.0
```

**Comment by mutkach** [comment]
statvfs.h is the correct FreeBSD variant, though the struct itself works different so chaning the header doesn't work.
Fixed it by commenting out some statfs stuff in lev/vendor/ev.c
Works fine.

**Comment by avysk** [comment]
Any chance to try the fix?

**Comment by mutkach** [comment]
as a hotfix just put these lines
#if __FreeBSD__
#define EV_USE_INOTIFY 0
#define EV_USE_KQUEUE 1
#endif
in the line 509 before 
#if EV_USE_INOTIFY
file submodules/lev/lev/vendor/ev.c

**Comment by avysk** [comment]
I had to install yarn and a bunch of opam packages but then `make install` worked on 13.2-RELEASE-p2 arm64. Thanks!

**Comment by mro** [comment]
Hi @rgrinberg,

bumped into this issue (FreeBSD 14.1) - how would I go about, just manually patch as https://github.com/ocaml/ocaml-lsp/issues/1069#issuecomment-1684916146 mentions and then `$ opam install ocaml-lsp-server` again?

Feels quite hacky.

**Comment by rgrinberg** [comment]
Submitting a PR to https://github.com/rgrinberg/lev would be a good first step.
