### PR TITLE
Restore 4.06 support

### PR DESCRIPTION
**Pull request by prometheansacrifice**

### CODE REVIEW

**Comment by rgrinberg** [comment]
I've tested it out and it seems to work on 4.06 and it works fine.

**Comment by prometheansacrifice** [comment]
CI fails with `# File "vendor/merlin/src/ocaml/preprocess/parser_raw.ml", line 5, characters 2-42:
# Error: Unbound value MenhirLib.StaticVersion.require_20190924` which should go away once [rgrinberg/merlin#2](https://github.com/rgrinberg/merlin/pull/2) is merged.

Tested find at vscode-merlin with my fork: https://github.com/arrowresearch/vscode-merlin/pull/49

**Comment by prometheansacrifice** [comment]
We forgot to update the merlin submodule to [rgrinberg/merlin#fb90bf00d3](https://github.com/rgrinberg/merlin/commit/fb90bf00d3c6b444efc1f38f4c8ca282e8d52a8e)

**Comment by prometheansacrifice** [comment]
Also, should I look into 4.07 support? Or do you think we can revisit it later?

**Comment by rgrinberg** [comment]
I think it's fine to revisit it later.

> We forgot to update the merlin submodule to rgrinberg/merlin#fb90bf00d3

Could you send a PR for this?
